name: Build on Push & Pull Request
on: 
  push:
    branches:
      ["release-4.9.0"]
  pull_request:
    branches:
      ["release-4.9.0"]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'temurin'
      
      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: maven-settings-xml-action
        uses: whelk-io/maven-settings-xml-action@v20
        with:
          servers: >
            [
              {
                "id": "github-utils",
                "username": "${env.GITHUB_USERNAME}",
                "password": "${env.GITHUB_TOKEN}"
              },
              {
                "id": "github-dao",
                "username": "${env.GITHUB_USERNAME}",
                "password": "${env.GITHUB_TOKEN}"
              },
              {
                "id": "github-adapter",
                "username": "${env.GITHUB_USERNAME}",
                "password": "${env.GITHUB_TOKEN}"
              }
            ]
          output_file: $GITHUB_WORKSPACE/settings.xml
        env:
          GITHUB_USERNAME: ${{ secrets.GH_USERNAME }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      
      - name: Build and analyze
        env:
          GITHUB_USERNAME: ${{ secrets.GH_USERNAME }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          cat $GITHUB_WORKSPACE/settings.xml
          mvn -s $GITHUB_WORKSPACE/settings.xml clean install -DskipTests
    